### ISSUE TITLE
INfografia Melissa

### ISSUE THREAD

**Issue by mel-16** [SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-mel-16#2]
[Melissa.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-mel-16/files/12457995/Melissa.pdf)

**Comment by Aricel117** [comment]
Calif: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
